-- 1
SELECT MAX(SALARY)
FROM hr.employees;

-- 2
SELECT MAX(SALARY) - MIN(SALARY) AS 'Salary Diff'
FROM hr.employees;

-- 3
SELECT JOB_ID, AVG(SALARY)
FROM hr.employees
GROUP BY JOB_ID
ORDER BY AVG(SALARY) DESC;

-- 4
SELECT SUM(SALARY)
FROM hr.employees;

-- 5
SELECT
	ROUND(MAX(SALARY), 2),
    ROUND(MIN(SALARY), 2),
    ROUND(SUM(SALARY), 2),
    ROUND(AVG(SALARY), 2)
FROM hr.employees;

-- 6
SELECT COUNT(*)
FROM hr.employees
WHERE JOB_ID = 'IT_PROG';

-- 7
SELECT JOB_ID, SUM(SALARY)
FROM hr.employees
GROUP BY JOB_ID;

-- 8
SELECT JOB_ID, SUM(SALARY)
FROM hr.employees
GROUP BY JOB_ID
HAVING JOB_ID = 'IT_PROG';
-- -- OR (LESSER COST)
SELECT JOB_ID, SUM(SALARY)
FROM hr.employees
WHERE JOB_ID = 'IT_PROG';

-- 9
SELECT JOB_ID, AVG(SALARY) AS AVERAGE_SALARY
FROM hr.employees
GROUP BY JOB_ID
HAVING JOB_ID <> 'IT_PROG'
ORDER BY AVERAGE_SALARY DESC;

-- 10
SELECT
	DEPARTMENT_ID,
    AVG(SALARY) AS AVERAGE_SALARY,
    COUNT(*) AS NUMBER_EMPLOYEES
FROM hr.employees
GROUP BY DEPARTMENT_ID
HAVING NUMBER_EMPLOYEES > 10;
    