-- 1
SELECT MAX(SALARY)
FROM hr.employees;

-- 2
SELECT MAX(SALARY) - MIN(SALARY) AS 'Salary Diff'
FROM hr.employees;

-- 3
SELECT JOB_ID, AVG(SALARY)
FROM hr.employees
GROUP BY JOB_ID
ORDER BY AVG(SALARY) DESC;

-- 4
SELECT SUM(SALARY)
FROM hr.employees;

-- 5
SELECT
	ROUND(MAX(SALARY), 2),
    ROUND(MIN(SALARY), 2),
    ROUND(SUM(SALARY), 2),
    ROUND(AVG(SALARY), 2)
FROM hr.employees;

-- 6
SELECT COUNT(*)
FROM hr.employees
WHERE JOB_ID = 'IT_PROG';

-- 7
SELECT JOB_ID, SUM(SALARY)
FROM hr.employees
GROUP BY JOB_ID;

-- 8
SELECT JOB_ID, SUM(SALARY)
FROM hr.employees
GROUP BY JOB_ID
HAVING JOB_ID = 'IT_PROG';
-- -- OR (LESSER COST)
SELECT JOB_ID, SUM(SALARY)
FROM hr.employees
WHERE JOB_ID = 'IT_PROG';

-- 9
SELECT JOB_ID, AVG(SALARY) AS AVERAGE_SALARY
FROM hr.employees
GROUP BY JOB_ID
HAVING JOB_ID <> 'IT_PROG'
ORDER BY AVERAGE_SALARY DESC;

-- 10
SELECT
	DEPARTMENT_ID,
    AVG(SALARY) AS AVERAGE_SALARY,
    COUNT(*) AS NUMBER_EMPLOYEES
FROM hr.employees
GROUP BY DEPARTMENT_ID
HAVING NUMBER_EMPLOYEES > 10;

-- 11
SET SQL_SAFE_UPDATES = 0;

UPDATE hr.employees
SET PHONE_NUMBER = REPLACE(PHONE_NUMBER, '515.', '777.')
WHERE PHONE_NUMBER LIKE '515.%';

-- 12
SELECT * FROM hr.employees
WHERE LENGTH(FIRST_NAME) >= 8;

-- 13
SELECT
	EMPLOYEE_ID,
    FIRST_NAME,
    YEAR(HIRE_DATE) AS HIRE_YEAR
FROM hr.employees;

-- 14
SELECT
	EMPLOYEE_ID,
    FIRST_NAME,
    DAY(HIRE_DATE) AS HIRE_DAY
FROM hr.employees;

-- 15
SELECT
	EMPLOYEE_ID,
    FIRST_NAME,
    MONTH(HIRE_DATE) AS HIRE_MONTH
FROM hr.employees;

-- 16
SELECT
	UCASE(CONCAT(FIRST_NAME, ' ', LAST_NAME))
FROM hr.employees;

-- 17
SELECT LAST_NAME, HIRE_DATE
FROM hr.employees
WHERE MONTH(HIRE_DATE) = 7 AND YEAR(HIRE_DATE) = 1987;

-- 18
SELECT
	FIRST_NAME,
    LAST_NAME,
    DATEDIFF(CURRENT_DATE(), HIRE_DATE)
FROM hr.employees;
